repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: local
    hooks:
    -   id: template-validator
        name: Check template syntax
        entry: python app/utils/template_validator.py
        language: python
        types: [file]
        files: \.html$
        pass_filenames: false
        
    -   id: template-best-practices-reminder
        name: Remind about template best practices
        entry: echo "Remember to follow template best practices from docs/template_best_practices.md"
        language: system
        files: \.html$
        pass_filenames: false
